apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-ribd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-ribd@sha256:b146e983cbee6991c1043fe733c3736e4c2c9b596e594bb4c84a41f5019c4f61
        name: my-nodejs
        resources: {}
status: {}
